---
- name: Setup Apache Web Server with Variable-based Configuration
  hosts: webservers
  become: yes
  vars:
    apache_port: 80
    document_root: /var/www/html
    enable_ssl: false
    network_utilities:
      - curl
      - wget

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # using loops to install multiple packages
    - name: Install network utilities
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ network_utilities }}"

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    # using conditionals
    - name: Install SSL module for Apache
      apt:
        name: openssl
        state: present
      when: enable_ssl == true

    - name: Enable SSL module
      shell: a2enmod ssl
      when: enable_ssl
      ignore_errors: yes

    - name: Enable Apache2 service
      shell: service apache2 start || /usr/sbin/apache2ctl start
      ignore_errors: yes

    - name: Copy index.html to web server
      template:
        src: /etc/ansible/assets/index.html
        dest: "{{ document_root }}/index.html"
        mode: '0644'

    - name: Restart Apache2
      shell: service apache2 restart || /usr/sbin/apache2ctl restart
      ignore_errors: yes
