services:
  ansible-master:
    image: ansible-dynamic-inventory-master
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-master
    hostname: ansible-master
    volumes:
      - ./playbooks:/etc/ansible/playbooks
      - ./inventory.py:/etc/ansible/inventory.py
      - ./ansible.cfg:/etc/ansible/ansible.cfg
    networks:
      - ansible-net
    stdin_open: true
    tty: true
    depends_on:
      - node1
      - node2

  node1:
    image: ubuntu:24.04
    container_name: node1
    hostname: node1
    networks:
      - ansible-net
    ports:
      - "8001:80"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      /bin/bash -c "
        apt-get update &&
        apt-get install -y openssh-server python3 &&
        echo 'root:testpass' | chpasswd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        mkdir -p /run/sshd &&
        /usr/sbin/sshd -D
      "

  node2:
    image: ubuntu:24.04
    container_name: node2
    hostname: node2
    networks:
      - ansible-net
    ports:
      - "8002:80"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      /bin/bash -c "
        apt-get update &&
        apt-get install -y openssh-server python3 &&
        echo 'root:testpass' | chpasswd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        mkdir -p /run/sshd &&
        /usr/sbin/sshd -D
      "

networks:
  ansible-net:
    driver: bridge
