apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/alex-carvalho/sandbox.git
      revision: HEAD
      files:
      - path: "devops/gitops/argocd/examples/using-applicationset/apps/*.yaml"
  template:
    metadata:
      name: '{{app.name}}'
    spec:
      project: default
      source:
        repoURL: '{{app.repoURL}}'
        targetRevision: '{{app.targetRevision}}'
        path: '{{app.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{app.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
