app:
  name: prometheus
  namespace: monitoring
  helmRepo: https://prometheus-community.github.io/helm-charts
  chart: prometheus
  version: 25.30.1
  values: |
    server:
      persistentVolume:
        enabled: false
    alertmanager:
      enabled: false
