services:
  ansible-master:
    image: ansible-master-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-master
    hostname: ansible-master
    volumes:
      - ./playbooks:/etc/ansible/playbooks
      - ./inventory:/etc/ansible/inventory
      - ./host_vars:/etc/ansible/host_vars
      - ./roles:/etc/ansible/roles
      - ./assets:/etc/ansible/assets
      - ./ansible.cfg:/etc/ansible/ansible.cfg
    networks:
      - ansible-net
    stdin_open: true
    tty: true
    depends_on:
      - node1
      - node2

  node1:
    image: ansible-node
    build:
      context: ../shared/node
    container_name: node1
    hostname: node1
    networks:
      - ansible-net
    ports:
      - "8001:80"

  node2:
    image: ansible-node
    build:
      context: ../shared/node
    container_name: node2
    hostname: node2
    networks:
      - ansible-net
    ports:
      - "8002:80"

networks:
  ansible-net:
    driver: bridge
